export const library = [
  {
    bookshelf: "Alfa",
    authors: [
      "Daniel Defoe",
      "William Shakespeare",
      "Benjamin Disraeli",
      "Robert Stevenson",
      "Thomas Hardy",
      "Conan Doyle",
      "Rudyard Kipling",
    ],
    subscribers: 43,
    isOpen: true,
    isIllustrated: "some",
  },
  {
    bookshelf: "Bravo",
    authors: [
      "John Locke",
      "John Milton",
      "Thomas Hardy",
      "William Shakespeare",
    ],
    subscribers: 90,
    isOpen: true,
    isIllustrated: "none",
  },
  {
    bookshelf: "Charlie",
    authors: [
      "Charles Dickens",
      "Jonathan Swift",
      "Walter Scott",
      "Conan Doyle",
      "Rudyard Kipling",
    ],
    subscribers: 19,
    isOpen: false,
    isIllustrated: "all",
  },
  {
    bookshelf: "Delta",
    authors: [
      "Charlotte Brontë",
      "Jonathan Swift",
      "Thomas Hobbes",
      "John Locke",
      "William Shakespeare",
      "Jerome Klapka Jerome",
    ],
    subscribers: 50,
    isOpen: true,
    isIllustrated: "some",
  },
];
